### ISSUE TITLE
Upload doesn't work in live deployment

### ISSUE THREAD

**Issue by rrojan** [Shuffle10/ShutterSquad#1]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/59971845/232239391-f70552a5-51e2-455c-b42a-9cdf44af5427.png">
<img width="696" alt="image" src="https://user-images.githubusercontent.com/59971845/232239400-f28ca288-f8c6-45af-960f-051f27ba3e7e.png">

Most probably this is because you're using signed images, which is a secure way of storing static assets, but needs a pre-request to sign the image

**Comment by Shuffle10** [comment]
This is strange! It was working everywhere I tested and this image is also uploaded in my cloudinary bbucket. Anyways, I have added async await for imagedataUpdate. Hope this works
